name: Test Manual Workflow

on:
  workflow_dispatch: # Объявляем, что workflow можно запустить вручную

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello from manual workflow!"
